
trigger:
- master
- mr/*

pr:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: mbeutel/CImakeshift
      endpoint: mbeutel
      #ref: refs/tags/0.2

jobs:
- template: azure-pipelines-job-cmake.yml@templates
  parameters:
    vcpkgRef: bc01338fe2d50f4a24b7f56b53bc385d8de8ccd9
    vcpkgOverlayRepo: 'https://mp-force.ziti.uni-heidelberg.de/asc/infrastructure/vcpkg-ports.git'
    vcpkgOverlayRef: a3af41edd36c5a2be17d44f2da0085db11b36331
    vcpkgPackages: ['cmakeshift', 'gsl-lite', 'catch2']

    cmakeBuildConfigurations: [Debug]
    cmakeConfigArgs: '-DSYSMAKESHIFT_BUILD_TESTS=ON'

    targets:

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [7, 8]
      platforms: [x64]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [9]
      platforms: [x64]
      displayTag: 'sanitize'
      vcpkgTriplet: <platform>-<os>-sanitize
      cmakeConfigArgs: '-DCMAKESHIFT_PRIVATE_COMPILE_SETTINGS=runtime-checks;debug-stdlib'

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [5, 6, 7, 8]
      platforms: [x64]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [9]
      platforms: [x64]
      displayTag: 'sanitize'
      vcpkgTriplet: <platform>-<os>-sanitize
      cmakeConfigArgs: '-DCMAKESHIFT_PRIVATE_COMPILE_SETTINGS=runtime-checks;debug-stdlib'

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_1, 19_2]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: Clang
      cxxCompilerVersions: [9]
      platforms: [x86, x64]

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [7, 8, 9]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [10, 10_0_1, 11]
      platforms: [x64]
