
trigger:
- master
- mr/*

pr:
- master

resources:
  repositories:
    - repository: CImakeshift
      type: github
      name: mbeutel/CImakeshift
      endpoint: mbeutel

jobs:
- template: azure-pipelines/cmake.yml@CImakeshift
  parameters:
    vcpkgRef: ca846b21276c9a3171074ac8d2b4f6516894a7d0

    cmakeBuildConfigurations: [Debug]

    targets:

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [VS2022]
      platforms: [x86, x64]
      tag: 'optimized'
      cmakeBuildConfigurations: [RelWithDebInfo]
      cmakeConfigPreset: 'ci-msvc'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [14]
      platforms: [x64]
      tag: 'optimized'
      cmakeBuildConfigurations: [RelWithDebInfo]
      cmakeConfigPreset: 'ci-gcc'

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [16_0]
      platforms: [x64]
      tag: 'optimized'
      cmakeBuildConfigurations: [RelWithDebInfo]
      cmakeConfigPreset: 'ci-clang'

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [VS2019, VS2022]
      platforms: [x86, x64]
      cmakeConfigPreset: 'ci-msvc'

    - os: Windows
      cxxCompiler: Clang
      cxxCompilerVersions: [VS2019, VS2022]
      platforms: [x86, x64]
      cmakeConfigPreset: 'ci-clang-cl'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [12, 13]
      platforms: [x64]
      cmakeConfigPreset: 'ci-gcc'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [14]
      platforms: [x64]
      tag: 'sanitize'
      cmakeConfigPreset: 'ci-gcc-sanitize'

    #- os: Linux
    #  cxxCompiler: Clang
    #  cxxCompilerVersions: [19]
    #  platforms: [x64]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [19]
      platforms: [x64]
      tag: 'sanitize'
      cmakeConfigPreset: 'ci-clang-sanitize'

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [19]
      platforms: [x64]
      tag: 'optimized'
      cmakeBuildConfigurations: [Release]
      cmakeConfigPreset: 'ci-clang'

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [12, 13]
      platforms: [x64]
      cmakeConfigPreset: 'ci-gcc'

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [14]
      platforms: [x64]
      tag: 'optimized'
      cmakeBuildConfigurations: [Release]
      cmakeConfigPreset: 'ci-gcc'

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [16_0]
      platforms: [x64]
      cmakeConfigPreset: 'ci-clang'
